#! /bin/sh
srcdir="`dirname $0`"
binutils_version="2.27"
gcc_version="6.2.0"
sysroot=""

for i in "$@"
do
case $i in
	--sysroot=*)
		sysroot=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
		;;
	
	--binutils-version=*)
		binutils_version=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
		;;
	
	--gcc-version=*)
		gcc_version=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
		;;
	
	*)
		echo >&2 "$0: unrecognised command-line option: $i"
		exit 1
		;;
esac
done

if [ "`ls`" != "" ]
then
	echo >&2 "$0: you must run me in an empty directory"
	exit 1
fi

if [ "$sysroot" = "" ]
then
	echo >&2 "$0: you must specify a --sysroot for the cross-compiler"
	exit 1
fi

if [ ! -f $srcdir/binutils/binutils-$binutils_version.patch ]
then
	echo >&2 "$0: no patch for version $binutils_version of binutils!"
	exit 1
fi

echo "Downloading binutils..."
rm -f binutils-$binutils_version.tar.gz
wget https://ftp.gnu.org/gnu/binutils/binutils-$binutils_version.tar.gz || exit 1
tar -xzf binutils-$binutils_version.tar.gz || exit 1
mv binutils-$binutils_version glidix-binutils || exit 1
tar -xzf binutils-$binutils_version.tar.gz || exit 1

echo "Downloading GCC..."
rm -f gcc-$gcc_version.tar.gz
wget http://nl.mirror.babylon.network/gcc/releases/gcc-$gcc_version/gcc-$gcc_version.tar.gz || exit 1
tar -xzf gcc-$gcc_version.tar.gz || exit 1
mv gcc-$gcc_version glidix-gcc || exit 1
tar -xzf gcc-$gcc_version.tar.gz || exit 1

echo "Patching binutils..."
cd glidix-binutils
patch -p1 < ../$srcdir/binutils/binutils-$binutils_version.patch || exit 1
cd ..

echo "Patching GCC..."
cd glidix-gcc
patch -p1 < ../$srcdir/gcc/gcc-$gcc_version.patch || exit 1
cd ..

echo "Generating install script..."
echo >install.sh "#! /bin/sh"
echo >>install.sh "GCC_VERSION=$gcc_version"
echo >>install.sh "BINUTILS_VERSION=$binutils_version"
echo >>install.sh "SRCDIR=$srcdir"
echo >>install.sh "SYSROOT=$sysroot"
cat >>install.sh $srcdir/crosstools-install
chmod +x install.sh

echo "Generating make-patches script..."
echo >make-patches.sh "#! /bin/sh"
echo >>make-patches.sh "diff -urN binutils-$binutils_version glidix-binutils > binutils-$binutils_version.patch"
echo >>make-patches.sh "diff -urN gcc-$gcc_version glidix-gcc binutils-$binutils_version.patch"
chmod +x make-patches.sh
