.PHONY: all install clean distclean
all:
	python build.py
install:
	sh install.sh /glidix
clean:
	rm -rf build build.mk libglidix.o config.json Makefile
distclean:
	rm -rf build build.mk libglidix.o config.json Makefile out
