/*
	Glidix Shell Utilities

	Copyright (c) 2014-2017, Madd Games.
	All rights reserved.
	
	Redistribution and use in source and binary forms, with or without
	modification, are permitted provided that the following conditions are met:
	
	* Redistributions of source code must retain the above copyright notice, this
	  list of conditions and the following disclaimer.
	
	* Redistributions in binary form must reproduce the above copyright notice,
	  this list of conditions and the following disclaimer in the documentation
	  and/or other materials provided with the distribution.
	
	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
	AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
	IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
	DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
	FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
	DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
	SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
	CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
	OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
	OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include <sys/glidix.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>

int haveDevice(uint16_t vendor, uint16_t device)
{
	int i;
	_glidix_pcidev dev;
	for (i=0;;i++)
	{
		if (_glidix_pcistat(i, &dev, sizeof(_glidix_pcidev)) == -1)
		{
			return 0;
		};
		
		if ((dev.vendor == vendor) && (dev.device == device))
		{
			return 1;
		};
	};
};

int main(int argc, char *argv[])
{
	if (argc != 2)
	{
		fprintf(stderr, "USAGE:\t%s <pathname>\n", argv[0]);
		fprintf(stderr, "\tAutomatically generate a gwm.conf file at the specified location.\n");
		return 1;
	};
	
	FILE *fp = fopen("/etc/dispdevs.dat", "r");
	if (fp == NULL)
	{
		fprintf(stderr, "%s: could not open /etc/dispdevs.dat: %s\n", argv[0], strerror(errno));
		return 1;
	};
	
	char devname[1024];
	devname[0] = 0;
	
	char linebuf[1024];
	char *line;
	int lineno = 0;
	while ((line = fgets(linebuf, 1024, fp)) != NULL)
	{
		lineno++;
		char *endline = strchr(line, '\n');
		if (endline != NULL)
		{
			*endline = 0;
		};
		
		if (strlen(line) >= 1023)
		{
			fprintf(stderr, "%s: /etc/dispdevs.dat:%d: buffer overflow\n", argv[0], lineno);
			return 1;
		};
		
		uint16_t vendor, device;
		if ((sscanf(line, "%4hx:%4hx %s", &vendor, &device, devname) == 3))
		{
			if (haveDevice(vendor, device))
			{
				break;
			};
		}
		else if (line[0] == '#')
		{
			continue;
		}
		else if (strlen(line) == 0)
		{
			continue;
		}
		else
		{
			fprintf(stderr, "%s: /etc/dispdevs.dat:%d: syntax error\n", argv[0], lineno);
			return 1;
		};
	};
	
	fclose(fp);
	
	if (devname[0] == 0)
	{
		// no native graphics device detected; just use the boot framebuffer
		strcpy(devname, "bootfb");
	};
	
	fp = fopen(argv[1], "w");
	if (fp == NULL)
	{
		fprintf(stderr, "%s: could not write to %s: %s\n", argv[0], argv[1], strerror(errno));
		return 1;
	};
	
	fprintf(fp, "# /etc/gwm.conf\n");
	fprintf(fp, "# GWM configuration file, generated by dispconf(1)\n");
	fprintf(fp, "display /dev/%s0\n", devname);
	fprintf(fp, "resolution auto\n");
	fprintf(fp, "log /dev/com2\n");
	fclose(fp);
	
	return 0;
};
