#! /bin/sh
# USAGE: modcc <input-file> <output-file>
x86_64-glidix-gcc -c $1 -o $2 -ffreestanding -mcmodel=large -mno-red-zone -mno-mmx -mno-sse -mno-sse2 -fno-common -fno-builtin -I /glidix/kernel-include -Wall -Werror
