#! /bin/sh
# mip-setup <filename>
# Create a MIP package named "filename" from files created by installation
# using "make install". Basically it runs "DESTDIR=/glidix/mipdir make install"
# and uses "/glidix/mipdir" as the root of the MIP package.

if [ "`id -u`" != "0" ]
then
	echo "$0: you must be root" 1>&2
	exit 1
fi

rm -rf /glidix/mipdir
mkdir -p /glidix/mipdir
DESTDIR=/glidix/mipdir make install
mkmip /glidix/mipdir $1
